version: '1.0'
services:
  node-server:
    container_name: 'node-mongo'
    build: .
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - node-mongo-data:/data/db
volumes:
  node-mongo-data: